name: Validate-GitHub-Actions
run-name: ${{ github.sha }}_${{ github.run_id }}
on: [push]
defaults:
  run:
    shell: bash
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install action-validator with asdf
        uses: asdf-vm/actions/install@v2
        with:
          tool_versions: |
            action-validator 0.1.2
      - name: Lint Actions
        run: |
          find .github/workflows -type f \( -iname \*.yaml -o -iname \*.yml \) \
            | xargs -I {} action-validator --verbose {}